name: CI-compile

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build OPL ELF
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip gawk bash

    - name: git checkout
      uses: actions/checkout@v4

    - name: Setup Git safe directory
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow || true

    - name: Compile OPL ELF
      run: |
        make clean || true
        make all

    - name: Upload release artifact ELF
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: OPNPS2LD
        path: |
          OPNPS2LD.ELF
          OPNPS2LD-*.ELF
          opl.elf
          *.ELF
